image: php:latest

pipelines:
    pull-requests:
        develop:
            - step:
                  name: Deploy to Test
                  caches:
                      - composer
                  deployment: test
                  script:
                      - echo "Deploying to Test"
                      - apt-get update && apt-get install -y unzip git git-core libc-client-dev libkrb5-dev
                      # - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
                      # - composer install
                      - git remote add github ${GITHUB_REPO}
                      - git push github master
                      - git push github release/${RELEASE_VERSION_NUMBER}
                      - git push --tags github
    branches:
        master: # Test, Build and Deploy
            - step:
                  name: Unit Test
                  caches:
                      - composer
                  script:
                      - echo "Running Unit Test"
            - step:
                  name: Deploy to Test
                  caches:
                      - composer
                  deployment: test
                  script:
                      - echo "Deploying to Test"
            - step:
                  name: Deploy to Production
                  trigger: manual
                  deployment: production
                  caches:
                      - composer
                  script:
                      - echo "Deploying to Production"
                      # - npm run deploy
                      # - npm run test:e2e
                      - composer run-script deploy
